name: desafio
description: A sample command-line application.
version: 1.0.0
repository: https://github.com/IguJl15/desafio-soma-multiplos
publish_to: none

environment:
  sdk: ^2.12.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
